# Generated by Django 3.1.5 on 2021-01-09 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=50, unique=True)),
                ('arxiv_version', models.IntegerField()),
                ('title', models.TextField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField(db_index=True)),
                ('summary', models.TextField()),
                ('authors', models.JSONField()),
                ('arxiv_url', models.URLField()),
                ('pdf_url', models.URLField()),
                ('primary_category', models.CharField(max_length=100)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('comment', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_ref', models.TextField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'get_latest_by': 'updated',
            },
        ),
    ]
