# Generated by Django 3.1.5 on 2021-01-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'get_latest_by': 'updated', 'ordering': ['updated']},
        ),
    ]
