# Generated by Django 3.1.5 on 2021-01-16 03:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='prefer_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['cs.CL', 'cs.LG', 'cs.CV', 'cs.AI', 'cs.IR', 'stat.ML', 'math.OC'], size=None),
        ),
    ]
