# Generated by Django 3.1.5 on 2021-01-16 03:50

import django.contrib.postgres.fields
from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210115_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='prefer_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=webapp.models.UserPreference.get_prefer_categories_default, size=None),
        ),
    ]
