# Generated by Django 3.1.5 on 2021-01-17 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_auto_20210116_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ManyToManyField(through='webapp.UserPaper', to=settings.AUTH_USER_MODEL),
        ),
    ]
