# Generated by Django 3.1.5 on 2021-01-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_paper_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpaper',
            old_name='read',
            new_name='read_state',
        ),
    ]
