# Generated by Django 3.1.5 on 2021-02-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_paper_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='authors_str',
            new_name='authors',
        ),
    ]
