# Generated by Django 3.1.5 on 2021-02-20 07:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210220_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=['N/A'], size=None),
            preserve_default=False,
        ),
    ]
