# Generated by Django 3.1.5 on 2021-02-20 19:26

from django.db import migrations, models
from tqdm import tqdm

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20210220_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='authors_m2m',
            field=models.ManyToManyField(to='webapp.Author'),
        ),
    ]
