# Generated by Django 3.1.5 on 2021-02-20 19:32

from django.db import migrations

from tqdm import tqdm

def convert_author(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Paper = apps.get_model('webapp', 'Paper')
    Author = apps.get_model('webapp', 'Author')
    for p in tqdm(Paper.objects.all()):
        for name in p.authors:
            author, created = Author.objects.get_or_create(name=name)
            p.authors_m2m.add(author)
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210220_1426'),
    ]

    operations = [
        migrations.RunPython(convert_author),
    ]
