# Generated by Django 3.1.5 on 2021-02-20 21:56

from django.db import migrations, models
from tqdm import tqdm

def convert_cats(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Paper = apps.get_model('webapp', 'Paper')
    Category = apps.get_model('webapp', 'Category')
    for p in tqdm(Paper.objects.all()):
        for name in set(p.categories):
            cat, created = Category.objects.get_or_create(name=name)
            p.categories_m2m.add(cat)
        p.save()

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210220_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='categories_m2m',
            field=models.ManyToManyField(to='webapp.Category'),
        ),
        migrations.RunPython(convert_cats),
    ]
