# Generated by Django 3.1.5 on 2021-02-23 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_userpaper_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaper',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
