# Generated by Django 3.1.5 on 2021-02-23 21:19

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20210223_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_summary_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
