# Generated by Django 3.1.5 on 2021-02-23 22:25

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20210223_1619'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_summary_search_vector'], name='webapp_pape_title_s_8907b2_gin'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_search_vector'], name='webapp_pape_title_s_430cb8_gin'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=django.contrib.postgres.indexes.GinIndex(fields=['summary_search_vector'], name='webapp_pape_summary_3c3359_gin'),
        ),
    ]
